name: hugo site

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Hugo Deploy GitHub Pages
      uses: benmatselby/hugo-deploy-gh-pages@1.1.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
