name: hugo site

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Master
      uses: actions/checkout@v2
    - name: Hugo Deploy GitHub Pages
      uses: benmatselby/hugo-deploy-gh-pages@1.1.0
      env:
        HUGO_VERSION: 0.63.2
        TARGET_REPO: XIEJD/xiejd.github.io.git
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        CNAME: www.shareif.cn
